[package]
name = "quex"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum_dispatch = "0.3.13"
pest = "2.7.10"
pest_derive = "2.7.10"
pulldown-cmark = "0.11.0"
time = "0.3.36"
zemen = "0.1.4"
